baseurl = "https://gabrielmiranda.me/"
# Shown in the side menu
copyright = "&copy; 2020. Some rights reserved."
canonifyurls = true
paginate = 10
theme = "LoveIt"
disqusShortname = "gabrielmiranda-me"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true


[author]
    name = "Gabriel Miranda (a.k.a gmiranda)"
    homepage = "https://gabrielmiranda.me"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:year/:month/:day/:title"

[taxonomies]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  truncate = true
  defaultDescription = "Sharing the code"
  hideReadingTime = false
  theme = "theme-base-07"
  home = "Home"
  github = "https://github.com/gabrielfmiranda"
  bitbucket = ""
  stackOverflow = "https://pt.stackoverflow.com/users/176046/gabriel-miranda"
  linkedin = "https://www.linkedin.com/in/gabriel8fm/"
  googleplus = ""
  facebook = ""
  twitter = "https://twitter.com/mirandafgabriel"

  [menu]
    # Shown in the side menu.
    [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 0
      identifier = "home"
      url = "/"
    [[menu.main]]
      name = "Portuguese"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 1
      identifier = "portuguese"
      url = "https://gabrielmiranda.me/tags/portugues"
    [[menu.main]]
      name = "English"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 2
      identifier = "english"
      url = "https://gabrielmiranda.me/tags/english"
    [[menu.main]]
      name = "About"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 3
      identifier = "about"
      url = "/about/"


  #  [[menu.main]]
  #    name = "Contact"
  #    pre = "<i class='fa fa-phone fa-fw'></i>"
  #    weight = 3
  #    url = "/contact/"
